export const yellow = '#FED500'
export const orange = '#FF9142'
export const red = '#ED315E'
export const purple = '#79129D'
export const blue = '#5350C7'
export const green = '#138800'
export const white = '#FFFFFF'

export const deepGrey = '#303030'
export const softGrey = '#AAAAAA'

// Gradients generated by https://coolors.co/gradient-palette
export const colors = {
  white: {
    default: '#FFFFFF',
    gradient: [
      'hsl(0, 0%, 93%)',
      'hsl(0, 0%, 75%)',
      'hsl(0, 0%, 56%)',
      'hsl(0, 0%, 37%)',
      'hsl(0, 0%, 19%)',
      'hsl(0, 0%, 0%)',
    ],
  },
  orange: {
    default: '#FF9142',
    gradient: [
      'hsl(25, 100%, 84%)',
      'hsl(25, 100%, 77%)',
      'hsl(25, 100%, 71%)',
      'hsl(25, 100%, 64%)',
      'hsl(25, 100%, 57%)',
      'hsl(25, 100%, 50%)',
    ],
  },
  red: {
    default: '#ED315E',
    gradient: [
      'hsl(347, 63%, 93%)',
      'hsl(346, 76%, 85%)',
      'hsl(346, 80%, 78%)',
      'hsl(346, 81%, 71%)',
      'hsl(346, 83%, 63%)',
      'hsl(346, 84%, 56%)',
    ],
  },
  purple: {
    default: '#79129D',
    gradient: [
      'hsl(284, 92%, 90%)',
      'hsl(284, 60%, 79%)',
      'hsl(284, 51%, 68%)',
      'hsl(285, 46%, 57%)',
      'hsl(285, 52%, 45%)',
      'hsl(284, 79%, 34%)',
    ],
  },
  blue: {
    default: '#5350C7',
    gradient: [
      'hsl(242, 100%, 93%)',
      'hsl(241, 70%, 86%)',
      'hsl(241, 61%, 78%)',
      'hsl(242, 56%, 70%)',
      'hsl(242, 53%, 62%)',
      'hsl(242, 52%, 55%)',
    ],
  },
  green: {
    default: '#138800',
    gradient: [
      'hsl(113, 100%, 95%)',
      'hsl(112, 49%, 81%)',
      'hsl(112, 42%, 68%)',
      'hsl(112, 39%, 54%)',
      'hsl(112, 55%, 40%)',
      'hsl(112, 100%, 27%)',
    ],
  },
  yellow: {
    default: '#FED500',
    gradient: [
      'hsl(50, 100%, 70%)',
      'hsl(50, 71%, 60%)',
      'hsl(50, 54%, 51%)',
      'hsl(50, 60%, 41%)',
      'hsl(51, 72%, 32%)',
      'hsl(51, 93%, 22%)',
    ],
  },
}
